version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: bowman
      DATABASE_PASSWORD: fillorbust
      NODE_ENV: development
    ports:
      - "8080:8080"
    command: npm run start-dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_DB: mussbuss
      POSTGRES_PASSWORD: fillorbust
      POSTGRES_USER: bowman
